import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import styles from '../styles/Home.module.css'
import Section1 from '../components/Section1'
import Section2 from '../components/Section2'
import Section3 from '../components/Section3'


export default function Home() {
  let hamburger= ''
  let navref= useRef(null);
  
 
    function toggleBotton(){
         
      navref.current.classList.toggle('show') 
      //navList.classList.toggle('show')
      console.log(navref.current);
    }

  return (
    <>
      <Head>
        <title>Raul Moya Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Raul_logo2.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap" rel="stylesheet"></link>
        <script src="https://kit.fontawesome.com/ba4de37315.js" crossorigin="anonymous"></script>
      </Head>
  
        
   
      <Section1/>
      <Section2/>
      <Section3/>

     
     
      <footer className={styles.bottom} id="contact-me">
        <h2>Contact Me:</h2>
        <p><strong>number: </strong>  (816) - 718 - 8927</p>
        <p><strong>email: </strong>  rauly7moya@gmail.com</p>
        <form   className={styles.form}>
          <label for="emal">Your Email</label>
          <input type="input" name="email" placeholder="your email" className={styles.input}/>
          <textarea rows="" cols="" placeholder="Type here" className={styles.textarea}></textarea>
          <button type="submit" className={styles.sendbutton}>Send</button>
        </form>
      </footer>
     
     
    </>
  )
}
